CC=gcc
challenge1=Day2.c
challenge2=Day2-2.c

all: Day2-challenge2

Day2-challenge1:
	$(CC) -o AOC2 $(challenge1)

Day2-challenge2:
	$(CC) -o AOC2-2 $(challenge2)

Clean:
	rm *.o
	rm AOC2
	rm AOC2-2
	rm *.dSYM